name: Django CI

on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "prod"

jobs:
  build:
    runs-on: 
      - self-hosted
      - label-1
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Dependencies for dev
      if: github.ref == 'refs/heads/dev'
      run: sudo docker compose up -d --build dev

    - name: Install Dependencies for prod
      if: github.ref == 'refs/heads/prod'
      run: sudo docker compose up -d --build prod

